### ISSUE TITLE
(حل لمشكلة كلمات مثل (الـٔاخرة

### ISSUE THREAD

**Issue by mohammad-sayed-ahmad** [quranacademy/quran-text#3]
السلام عليكم ورحمة الله وبركاته،
لقد وجدت حلا لمشكلة هذه الكلمات ألا وهو استعمال (ٵ) في اللغة الكزخية برمز U+0675
أي على سبيل المثال (الٵخرة)
شاكرين لجهود نقاية وجهودكم

**Comment by mustafa0x** [comment]
وعليكم السلام ورحمة الله وبركاته

شكرا على الاقتراح. جربته على أجهزتي. في بعضها ظهرت الكلمة صحيحا، وفي بعضها غير صحيح. يحتاج إلى تجربة أكثر وإلى كونه حلا صحيحا.

بالعفو.

**Comment by mohammad-sayed-ahmad** [comment]
شكرا على الرد!
